// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVXmB9G6YMdsuMdZ5-TN3UWDAf8lISSPw',
    appId: '1:304593744121:android:c7f1998f47d7846e057228',
    messagingSenderId: '304593744121',
    projectId: 'duba-debremewy-dogs-food-fbdb',
    storageBucket: 'duba-debremewy-dogs-food-fbdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkRTlCkUR-_UaM-yvnKPt3ABcEFfs2Khs',
    appId: '1:304593744121:ios:11c235b764888240057228',
    messagingSenderId: '304593744121',
    projectId: 'duba-debremewy-dogs-food-fbdb',
    storageBucket: 'duba-debremewy-dogs-food-fbdb.appspot.com',
    androidClientId: '304593744121-iir2tcldat78or7ktseit9rb36h7kemm.apps.googleusercontent.com',
    iosClientId: '304593744121-uc054l2mv636jecpomri6ni8rolhh1jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.dubaiDebremewyAppDogsFood',
  );
}
